# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QZPJtgUnYTQTXorR8vNZ6h9cu70fw9PB
"""

# STUDENT RECODE MANAGEMENT
students = []

def add_student():
    roll = input("Enter Roll Number: ")
    name = input("Enter Name: ")
    age = input("Enter Age: ")
    course = input("Enter Course: ")
    marks = input("Enter Marks: ")

    student = {
        "roll": roll,
        "name": name,
        "age": age,
        "course": course,
        "marks": marks
    }

    students.append(student)
    print("Student added successfully!\n")


def view_students():
    if not students:
        print("No student records found.\n")
        return

    print("\n--- Student Records ---")
    for s in students:
        print("Roll Number:", s["roll"])
        print("Name:", s["name"])
        print("Age:", s["age"])
        print("Course:", s["course"])
        print("Marks:", s["marks"])
        print("------------------------")


def search_student():
    roll = input("Enter Roll Number to search: ")

    for s in students:
        if s["roll"] == roll:
            print("\nStudent Found!")
            print("Roll Number:", s["roll"])
            print("Name:", s["name"])
            print("Age:", s["age"])
            print("Course:", s["course"])
            print("Marks:", s["marks"])
            return

    print("Student not found.\n")


def update_student():
    roll = input("Enter Roll Number to update: ")

    for s in students:
        if s["roll"] == roll:
            s["name"] = input("Enter New Name: ")
            s["age"] = input("Enter New Age: ")
            s["course"] = input("Enter New Course: ")
            s["marks"] = input("Enter New Marks: ")

            print("Student record updated successfully!\n")
            return

    print("Student not found.\n")


def delete_student():
    roll = input("Enter Roll Number to delete: ")

    for s in students:
        if s["roll"] == roll:
            students.remove(s)
            print("Student deleted successfully!\n")
            return

    print("Student not found.\n")


while True:
    print("\n===== Student Record Management System =====")
    print("1. Add Student")
    print("2. View Students")
    print("3. Search Student")
    print("4. Update Student")
    print("5. Delete Student")
    print("6. Exit")

    choice = input("Enter your choice: ")

    if choice == "1":
        add_student()
    elif choice == "2":
        view_students()
    elif choice == "3":
        search_student()
    elif choice == "4":
        update_student()
    elif choice == "5":
        delete_student()
    elif choice == "6":
        print("Thank you!")
        break
    else:
        print("Invalid choice. Please try again.")

# DSA PROJECT TASK SCHEDULAR (USING QUEUE)
from collections import deque

queue = deque()

while True:
    print("\n1. Add Task")
    print("2. Show Tasks")
    print("3. Run Task")
    print("4. Delete Task")
    print("5. Exit")

    choice = input("Enter choice: ")

    if choice == "1":
        task = input("Enter task: ")
        queue.append(task)
        print("Task added")

    elif choice == "2":
        print("Tasks:", list(queue))

    elif choice == "3":
        if queue:
            task = queue.popleft()
            print("Running:", task)
        else:
            print("No tasks")

    elif choice == "4":
        task = input("Enter task to delete: ")
        if task in queue:
            queue.remove(task)
            print("Task deleted")
        else:
            print("Task not found")

    elif choice == "5":
        print("Thank you!")
        break

    else:
        print("Invalid choice")

# Number Triange
n = 5
for i in range(1, n+1):
  for j in range(1, i+1):
    print(j, end=" ")
  print()

# Floyd's Triangle
n=5
num = 1
for i in range(1,n+1):
  for j in range(i):
    print(num, end=" ")
    num+=1
  print()

# Inverted Number Triangle
n=5
for i in range(n,0,-1):
  for j in range(1,i+1):
    print(j,end=" ")
  print()

#Number Pyramid
n=5
for i in range(1,n+1):
  for j in range(1,n-1+1):
    print (" ",end="")
  for j in range(1,i+1):
    print(j, end=" ")
  for j in range(i-1,0,-1):
    print(j,end=" ")
  print()

# Diamond Number Patter
#upper half
n=4
for i in range(1,n+1):
  for j in range(1,n-i+1):
    print(" ",end="")
  for j in range(1,2*i):
    print(j,end=" ")
  for j in range(2*i-2,i-1,-1):
    print(j,end=" ")
  print()
#lower half
for i in range(n-1,0,-1):
  for j in range(1,n-i+1):
    print(" ",end="")
  for j in range(1,2*i):
    print(j,end=" ")
  for j in range(2*i-2,i-1,-1):
    print(j,end=" ")
  print()

# Hollow Number Pyramid
n=5
for i in range(1,n+1):
  for j in range(1,2*i):
    if j==1 or j==2*i-1 or i==n:
      print(j if j<=i else 2*i-j,
            end=" ")
    else:
      print(" ",end=" ")
    print()

# Pascal's Triangle
n=5
for i in range(n):
  num = 1
  for j in range(i+1):
    print(num,end=" ")
    num = num*(i-j)//(j+1)
  print()

from re import L
#Number Diamond Pattern
n=4
# upper half
for i in range(1,n+1):
  for j in range(1,2*i):
    print(j if j <=i else 2*i-j,
          end=" ")
  print()
# lower half
for i in range(n-1,0,-1):
  for j in range(1,2*i):
    print(j if j<=i else 2*i-j,
          end=" ")
  print()

# Number Hourglass Pattern
n=3
#upper half
for i in range(1,n+1):
  for j in range(n-i):
    print(" ",end="")
  for j in range(1,i+1):
    print(j,end=" ")
  for j in range(i-1,0,-1):
    print(j,end=" ")
#lower half
for i in range(n-1,0,-1):
  for j in range(n-i):
    print(" ",end="")
  for j in range(1,i+1):
    print(j,end=" ")
  for j in range(i-1,0,-1):
    print(j,end=" ")

# Right Aligned Number Triangle
n=5
for i in range(1,n+1):
  for j in range(n-i):
    print(" ",end="")
  for j in range(1,i+1):
    print(j, end=" ")
  print()

# Number Hill Pattern
n=5
for i in range(1,n+1):
  for j in range(n-i):
    print(" ",end=" ")
  for j in range(1,i+1):
    print(j,end=" ")
  print()

# Number Hill Pattern
n=4
for i in range(1,n+1):
  for j in range(n-i):
    print(" ",end=" ")
  for j in range(1,i+1):
    print(j,end=" ")
  for j in range(i-1,0,-1):
    print(j,end=" ")
  print()

# Butterfly Number Pattern
n=5
# upper half
for i in range(1,n+1):
  for j in range(1,i+1):
    print(j,end=" ")
    for j in range(i-1,0,-1):
      print(j,end=" ")
  print()
#lower half
for i in range(n-1,0,-1):
  for j in range(1,i+1):
        print(j, end=" ")
        for j in range(i-1,0,-1):
          print(j, end=" ")
  print()

# Number X Pattern
n=5
for i in range(1,n+1):
  for j in range(1,n+1):
    if j==i or j==n-i+1:
      print(j,end=" ")
    else:
      print(" ", end=" ")
  print()

# Number Cross Pattern
n=5
for i in range(1,n+1):
  for j in range(1,n+1):
    if i==(n+1)//2 or \
     j==(n+1)//2:
     print(1,end=" ")
    else:
      print(" ",end=" ")
  print()

